package user;

public enum ReportUserReasons {

	HACKED_ACCOUNT,IMPERSONATION_ACCOUNTS,UNDERAGE_CHILDRED,HATE_ACCOUNTS,INTELLECTUAL_PROPERTY,
	EXPOSED_PRIVATE_INFORMATION,SELF_INJURY,ABUSE_SPAM,EXPLOITATION,OTHER
}
